name: Femdom Auto Reposter

on:
  schedule:
    - cron: "08 */4 * * *"   # <-- elke 4 uur
  workflow_dispatch:        # handmatig starten mogelijk

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install atproto

      - name: Run autoposter
        env:
          BSKY_USERNAME_FD: ${{ secrets.BSKY_USERNAME_FD }}
          BSKY_PASSWORD_FD: ${{ secrets.BSKY_PASSWORD_FD }}
        run: python autoposter_FD.py